---
- name: Install prerequisites
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
   # - apt-transport-https
   # - ca-certificates
   # - python3-pip
   - curl
   - software-properties-common


- name: Add RabbitMQ GPG key
  apt_key:
    url: https://www.rabbitmq.com/rabbitmq-release-signing-key.asc
    state: present
- name: Add RabbitMQ APT repository
  apt_repository:
    repo: 'deb http://www.rabbitmq.com/debian/ testing main'
    state: present
- name: Install RabbitMQ
  apt:
    name: rabbitmq-server


- name: enable rabbitmq plugins
  rabbitmq_plugin:
    names: rabbitmq_management,rabbitmq_tracing,rabbitmq_federation
    state: enabled
  notify:
  - restart rabbitmq

- name: add user
  rabbitmq_user:
    user: "{{ item }}"
    password: "{{ ADMIN_PASS }}"
    tags: administrator,{{item}}
    vhost: /
    configure_priv: .*
    write_priv: .*
    read_priv: .*
    state: present
  with_items:
  - admin



- name: Capturing Erlang Cookie On Master
  command: "cat {{ rabbitmq_erlang_cookie_file }}"
  become: true
  register: "rabbitmq_erlang_cookie"
  when: inventory_hostname == "rabbit-node1"

- name: Setting Erlang Cookie Of Master on Non-Master
  set_fact:
    rabbitmq_erlang_cookie: "{{ hostvars['rabbit-node1']['rabbitmq_erlang_cookie']['stdout'] }}"
  when: inventory_hostname != "rabbit-node1"

- name: Copy erlang cookie
  template:
    src: erlang.cookie.j2
    dest: "{{ rabbitmq_erlang_cookie_file }}"
    owner: rabbitmq
    group: rabbitmq
    mode: 0400
    # backing up in case the need to recover
    backup: yes
  become: true
  when: inventory_hostname != "rabbit-node1"
  notify:
  - restart rabbitmq
